steps:
  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/nishyman10/Demo.Test.git']
  
  # Install SonarScanner
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '-g', 'sonarqube-scanner']
  
  # Run SonarScanner for SAST
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build', 'sonar-scanner', '-Dsonar.host.url=https://sonarcloud.io', '-Dsonar.login=97a9691220b6b9b0ee85f340d3ae7fea0593d905']
    dir: 'src'  # Specify the directory where your code resides
