steps:
  # Step 1: Clone the Git repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/nishyman10/Demo.Test.git', 'source']
    
  # Step 2: Additional build steps
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mvn', 'source']
  
 # Step 3: Install SonarScanner CLI
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g sonarqube-scanner
  
  # Step 4: Scan the source code using SonarScanner CLI
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sonar-scanner \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=30d7ea8abc8f6da04194590366dffd73cbec51f2 \
        -Dsonar.projectKey=nishyman10_Demo.Test \
        -Dsonar.sources=source \
        -Dsonar.java.binaries=source/target/classes
