steps:
  # Checkout the source code
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/nishyman10/Demo.Test.git']
  
  #Execute SonarCloud Scan
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['verify', 'sonar:sonar','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=nishyman10','-Dsonar.projectKey=nishyman10_Demo.Test','-Dsonar.login=84928a51fd69add3260a84ebbe111a63ad1d55f4']
