apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: ci-cd-test
description: main application pipeline
serialPipeline:
 stages:
// - targetId: test
//   profiles: []
 - targetId: staging
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: test
description: development cluster
gke:
 cluster: projects/<<PROJECT_ID>>/locations/us-central1/clusters/test #Update with your product ID instead of <<PROJECT_ID>>
---


apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: staging
description: staging cluster
gke:
 cluster: projects/<<PROJECT_ID>>/locations/us-central1/clusters/staging #Update with your product ID instead of <<PROJECT_ID>>
---
